
all: pairs sorting count

pairs: 
	clang++ -g -Wall -O0 -o pairs Pairs.cpp

fastpairs: 
	clang++ -g -Wall -O0 -o fastpairs FastPairs.cpp

sorting:
	clang++ -g -Wall -O0 -o sorting SortingLab.cpp Record.cpp

count:
	clang++ -g -Wall -O0 -o count CountInversions.cpp

.PHONY: pairs sorting count
